# This workflow deploys battery cycler controller to development environment

name: Deployment of battery cycler controller datatypes to Pypi

on:
  push:
    branches:
      - 'cycler_datatypes'

  pull_request_review:

env:
  PACKAGE_NAME: wattrex-battery-cycler-controller-datatypes

jobs:

  build-package-on-push:
    name: QA and Build battery controller datatypes on push
    if: ${{ github.event_name == 'push' }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: wattrex-battery-cycler-controller-datatypes
      package-path: "code/datatypes"
      python-version: "3.10"

  build-package-on-pull-request:
    name: QA and Build battery controller datatypes on pull request
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.head.ref == 'cycler_datatypes' }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: wattrex-battery-cycler-controller-datatypes
      package-path: "code/datatypes"
      python-version: "3.10"

  publish-package:
    name: Publish package wattrex-battery-cycler-controller-datatypes to PyPi
    needs: build-package-on-pull-request
    if: ${{ github.event_name == 'pull_request_review' }} && ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: wattrex-battery-cycler-controller-datatypes
          path: ${{ github.event.pull_request.head.ref }}/dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ${{ github.event.pull_request.head.ref }}/dist/
